create table if not exists  public.tools
(
    code            varchar(255) not null
        primary key,
    additional_info varchar(255),
    description     varchar(255),
    icon            varchar(255),
    name            varchar(255),
    place_column    varchar(255),
    place_row       varchar(255),
    place_shelf     varchar(255),
    type            varchar(255)
        constraint tools_type_check
            check ((type)::text = ANY
        ((ARRAY ['CUTTING'::character varying, 'MEASURE'::character varying, 'HELPERS'::character varying])::text[]))
    );

TABLESPACE pg_default;

alter table tools
    owner to bogdan;

create table if not exists public.workers
(
    id         bigint not null
        primary key,
    department varchar(255)
        constraint workers_department_check
            check ((department)::text = ANY
        ((ARRAY ['DEPARTMENT_19'::character varying, 'MAIN_STORAGE'::character varying, 'SHARPENING'::character varying, 'STORAGE_OF_DECOMMISSIONED_TOOLS'::character varying])::text[])),
    first_name varchar(255),
    join_date  date,
    last_name  varchar(255),
    login      varchar(255),
    patronymic varchar(255),
    type       varchar(255)
        constraint workers_type_check
            check ((type)::text = ANY
                   ((ARRAY ['WORKER'::character varying, 'STORAGE_WORKER'::character varying])::text[]))
);

TABLESPACE pg_default;

alter table workers
    owner to bogdan;

create table if not exists public.storage_records
(
    id        bigint generated by default as identity
        primary key,
    amount    integer,
    tool_code varchar(255)
        constraint fkrwbvquho3lb9d452t569ddt5l
            references tools,
    worker_id bigint
        constraint fk8vluiwjqqt7ilbsct9wuqgbej
            references workers
);

TABLESPACE pg_default;

alter table storage_records
    owner to bogdan;

create table if not exists public.tools_transactions
(
    code varchar(255) not null
        primary key,
    name varchar(255)
);

TABLESPACE pg_default;

alter table tools_transactions
    owner to bogdan;

create table if not exists public.workers_transaction
(
    id         bigint not null
        primary key,
    department varchar(255)
        constraint workers_transaction_department_check
            check ((department)::text = ANY
        ((ARRAY ['DEPARTMENT_19'::character varying, 'MAIN_STORAGE'::character varying, 'SHARPENING'::character varying, 'STORAGE_OF_DECOMMISSIONED_TOOLS'::character varying])::text[])),
    first_name varchar(255),
    last_name  varchar(255)
);

TABLESPACE pg_default;

alter table workers_transaction
    owner to bogdan;

create table if not exists public.transactions
(
    id               bigint generated by default as identity
        primary key,
    amount           integer,
    transaction_date date,
    receiver_id      bigint
        constraint fkk162ocbhl9m2qu84rnf3kxqy2
            references workers_transaction,
    sender_id        bigint
        constraint fkoh2iep7bsbtvc6o7s63lqscki
            references workers_transaction,
    tool_code        varchar(255)
        constraint fkcm3mue2xukg8cma165l61ow9r
            references tools_transactions
);

TABLESPACE pg_default;

alter table transactions
    owner to bogdan;

create table if not exists public.jaws
(
    id               bigserial
        primary key,
    description      varchar(255),
    name             varchar(255) not null,
    operation_number varchar(255) not null,
    place_column     varchar(255),
    place_row        varchar(255),
    place_shelf      varchar(255)
);

TABLESPACE pg_default;

alter table jaws
    owner to bogdan;

create table if not exists public.jaw_photos
(
    id          bigserial
        primary key,
    create_date timestamp(6),
    file_name   varchar(255),
    url         varchar(255),
    jaws_id     bigint
        constraint fka3mwto64bn4jtupall1a44t6r
            references jaws
);

TABLESPACE pg_default;

alter table jaw_photos
    owner to bogdan;

create table if not exists public.users
(
    id       bigserial
        primary key,
    password varchar(255) not null,
    role     varchar(255) not null
        constraint users_role_check
            check ((role)::text = 'USER'::text),
    username varchar(255) not null
        constraint uk_r43af9ap4edm43mmtq01oddj6
            unique
);

TABLESPACE pg_default;

alter table users
    owner to bogdan;

