spring:
  application:
    name: security-auth-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: bogdan
    password: Bogdan3622897
    url: jdbc:mysql://109.196.164.168:3306/bogdan_db

  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect:
          MySQLDialect: org.hibernate.dialect.MySQLDialect
          hbm2ddl:
            auto: update

jwt:
  token:
    validity: 86400
  secret: united-engine-corporation

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true