spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: bogdan
    password: bogdan
    url: jdbc:postgresql://localhost:5432/diploma
  application:
    name: security-auth-server
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update




jwt:
  token:
    validity: 86400
  secret: united-engine-corporation

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
