spring:
  application:
    name: security-auth-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root1234
    url: jdbc:mysql://localhost:3306/mydb

  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        dialect:
          MySQLDialect: org.hibernate.dialect.MySQLDialect



jwt:
  token:
    validity: 86400
  secret: united-engine-corporation

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
springdoc:
  swagger-ui:
    path: /custom/swagger-ui
