
server:
  port: 8080


spring:
  application:
    name: my-gateway
  cloud:
    gateway:
      routes:
        - id: my-microservice-transactions
          uri: http://localhost:8084/
          predicates:
            - Path=/transactions/**
        - id: my-microservice-storage-records
          uri: http://localhost:8085/
          predicates:
            - Path=/records/**
        - id: my-microservice-jaws
          uri: http://localhost:8081/
          predicates:
            - Path=/jaws/**
