
server:
  port: 8080


spring:
  application:
    name: my-gateway
  cloud:
    gateway:
      routes:
        - id: my-microservice-tools
          uri: http://localhost:8083/
          predicates:
            - Path=/tools/**
        - id: my-microservice-workers
          uri: http://localhost:8082/
          predicates:
            - Path=/workers/**
        - id: my-microservice-jaws
          uri: http://localhost:8081/
          predicates:
            - Path=/jaws/**