spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jaws
    password: jaws
    url: jdbc:postgresql://localhost:5432/jaws
  application:
    name: transactions-server
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true