spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root1234
    url: jdbc:mysql://localhost:3306/mydb

  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
server:
  port: 8085

