spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: bogdan
    password: bogdan
    url: jdbc:postgresql://localhost:5432/diploma
  application:
    name: records-server
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true