spring:
  application:
    name: records-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root1234
    url: jdbc:mysql://localhost:3306/mydb

  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true