spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: bogdan
    password: bogdan
    url: jdbc:postgresql://database:5432/diploma
  application:
    name: jaws-server
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
jaws-server:
  server-url: http://213.171.28.91:8081/images/
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

  instance:
    prefer-ip-address: true